# Generated by Django 3.0.8 on 2020-09-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectworkplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('lflag', models.IntegerField(default=0)),
            ],
        ),
    ]
