# Generated by Django 3.1.1 on 2020-10-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mectworkplace', '0003_auto_20201012_2044'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
